version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: SuperSecret!23
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data
